keda:
  operator:
    replicaCount: 1

  metricsServer:
    replicaCount: 1

  webhooks:
    replicaCount: 1

  resources:
    operator:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    metricServer:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    webhooks:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

  logging:
    operator:
      level: info
      format: console
    webhooks:
      level: info
      format: console

  # Pour scheduler sur tous les nœuds Linux
  nodeSelector:
    kubernetes.io/os: linux

  tolerations: []

  crds:
    install: false